/* INSERT IN TO COURSE */
insert into Course (title) values ('Brown and yellow marshbird');
insert into Course (title) values ('Striped hyena');
insert into Course (title) values ('Armadillo, giant');
insert into Course (title) values ('Snake, eastern indigo');
insert into Course (title) values ('Ring-tailed possum');
insert into Course (title) values ('Heron, gray');
insert into Course (title) values ('Galah');
insert into Course (title) values ('Steller sea lion');
insert into Course (title) values ('Common wombat');
insert into Course (title) values ('Gull, dusky');
insert into Course (title) values ('Lesser flamingo');
insert into Course (title) values ('Crane, sarus');
insert into Course (title) values ('Asian false vampire bat');
insert into Course (title) values ('Yellow-crowned night heron');
insert into Course (title) values ('Eastern indigo snake');
insert into Course (title) values ('Lizard, blue-tongued');
insert into Course (title) values ('Common zebra');
insert into Course (title) values ('Australian magpie');
insert into Course (title) values ('Paradoxure');
insert into Course (title) values ('Cape white-eye');
insert into Course (title) values ('Southern right whale');
insert into Course (title) values ('Wallaby, tammar');
insert into Course (title) values ('Dove, mourning collared');
insert into Course (title) values ('Kangaroo, black-faced');
insert into Course (title) values ('Oriental white-backed vulture');
insert into Course (title) values ('Spotted wood sandpiper');
insert into Course (title) values ('Sea birds (unidentified)');
insert into Course (title) values ('African elephant');
insert into Course (title) values ('Owl, great horned');
insert into Course (title) values ('Cat, civet');
insert into Course (title) values ('Fringe-eared oryx');
insert into Course (title) values ('Kingfisher, malachite');
insert into Course (title) values ('White-throated monitor');
insert into Course (title) values ('Red-cheeked cordon bleu');
insert into Course (title) values ('Rose-ringed parakeet');
insert into Course (title) values ('Snake (unidentified)');
insert into Course (title) values ('Pacific gull');
insert into Course (title) values ('Dromedary camel');
insert into Course (title) values ('Whale, long-finned pilot');
insert into Course (title) values ('Alpaca');
insert into Course (title) values ('Otter, canadian river');
insert into Course (title) values ('Gaur');
insert into Course (title) values ('Dove, emerald-spotted wood');
insert into Course (title) values ('Gecko, ring-tailed');
insert into Course (title) values ('Lesser mouse lemur');
insert into Course (title) values ('Heron, black-crowned night');
insert into Course (title) values ('Wallaby, dama');
insert into Course (title) values ('Spoonbill, european');
insert into Course (title) values ('Otter, canadian river');
insert into Course (title) values ('Chestnut weaver');
insert into Course (title) values ('Godwit, hudsonian');
insert into Course (title) values ('Hare, arctic');
insert into Course (title) values ('Lion, steller sea');
insert into Course (title) values ('Tailless tenrec');
insert into Course (title) values ('Blue crane');
insert into Course (title) values ('Civet, small-toothed palm');
insert into Course (title) values ('Heron, gray');
insert into Course (title) values ('Waxbill, blue');
insert into Course (title) values ('Green heron');
insert into Course (title) values ('White-browed sparrow weaver');
insert into Course (title) values ('Deer, swamp');
insert into Course (title) values ('Common long-nosed armadillo');
insert into Course (title) values ('Mexican boa');
insert into Course (title) values ('Admiral, indian red');
insert into Course (title) values ('Red-necked wallaby');
insert into Course (title) values ('Armadillo, common long-nosed');
insert into Course (title) values ('Long-billed corella');
insert into Course (title) values ('Crake, african black');
insert into Course (title) values ('Canada goose');
insert into Course (title) values ('Great egret');
insert into Course (title) values ('Sun gazer');
insert into Course (title) values ('Waved albatross');
insert into Course (title) values ('White-winged dove');
insert into Course (title) values ('Galapagos penguin');
insert into Course (title) values ('Urial');
insert into Course (title) values ('Seal, common');
insert into Course (title) values ('Eleven-banded armadillo (unidentified)');
insert into Course (title) values ('African ground squirrel (unidentified)');
insert into Course (title) values ('Black and white colobus');
insert into Course (title) values ('Galapagos hawk');
insert into Course (title) values ('African jacana');
insert into Course (title) values ('Goose, knob-nosed');
insert into Course (title) values ('Wallaby, agile');
insert into Course (title) values ('Goose, andean');
insert into Course (title) values ('Wallaby, euro');
insert into Course (title) values ('Bat, madagascar fruit');
insert into Course (title) values ('Bleeding heart monkey');
insert into Course (title) values ('Ass, asiatic wild');
insert into Course (title) values ('Brown hyena');
insert into Course (title) values ('Long-necked turtle');
insert into Course (title) values ('Australian pelican');
insert into Course (title) values ('Snake-necked turtle');
insert into Course (title) values ('Seal, northern elephant');
insert into Course (title) values ('Dragon, asian water');
insert into Course (title) values ('Roller, lilac-breasted');
insert into Course (title) values ('Long-crested hawk eagle');
insert into Course (title) values ('Fox, grey');
insert into Course (title) values ('Phascogale, brush-tailed');
insert into Course (title) values ('Grey heron');
insert into Course (title) values ('Skink, african');
/* INSERT IN TO COURSEMATERIAL */
insert into Course_Material (COURSE_ID, url) values (1, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (2, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (3, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (4, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (5, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (6, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (7, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (8, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (9, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (10, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (11, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (12, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (13, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (14, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (15, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (16, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (17, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (18, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (19, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (20, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (21, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (22, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (23, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (24, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (25, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (26, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (27, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (28, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (29, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (30, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (31, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (32, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (33, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (34, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (35, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (36, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (37, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (38, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (39, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (40, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (41, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (42, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (43, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (44, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (45, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (46, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (47, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (48, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (49, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (50, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (51, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (52, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (53, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (54, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (55, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (56, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (57, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (58, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (59, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (60, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (61, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (62, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (63, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (64, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (65, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (66, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (67, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (68, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (69, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (70, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (71, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (72, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (73, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (74, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (75, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (76, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (77, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (78, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (79, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (80, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (81, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (82, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (83, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (84, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (85, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (86, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (87, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (88, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (89, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (90, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (91, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (92, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (93, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (94, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into Course_Material (COURSE_ID, url) values (95, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into Course_Material (COURSE_ID, url) values (96, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (97, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (98, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into Course_Material (COURSE_ID, url) values (99, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into Course_Material (COURSE_ID, url) values (100, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
/* INSERT IN TO STUDENT */
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Maving', 'Nancy', '2016-02-13', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Peatheyjohns', 'Fonsie', '2022-10-06', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Knoles', 'Fania', '2019-09-23', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Solomonides', 'Hew', '2020-06-10', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Rubinsaft', 'Malory', '2016-10-15', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Mival', 'Gaelan', '2020-12-16', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Plascott', 'Murray', '2021-02-01', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Coppenhall', 'Susanetta', '2021-02-23', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Monier', 'Mohammed', '2017-11-16', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Dalgarnowch', 'Grange', '2021-06-26', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Dutchburn', 'Farlay', '2016-05-30', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('D''Ambrosio', 'Jacques', '2022-09-16', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Booley', 'Magdalene', '2018-10-18', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Olech', 'Everett', '2022-09-12', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Venners', 'Jannel', '2021-07-13', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Pettifer', 'Kim', '2017-02-22', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Mighele', 'Abagael', '2019-01-06', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Findon', 'Hube', '2021-05-15', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Berriball', 'Lucais', '2021-10-28', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Ingray', 'Salli', '2022-05-16', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Gorriessen', 'Allsun', '2022-10-12', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Henkens', 'Kellsie', '2022-11-06', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Rustich', 'Maison', '2022-04-03', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Halliday', 'Dean', '2022-10-23', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Tregoning', 'Zachery', '2020-10-21', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('O''Brogane', 'Fletch', '2016-10-27', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Jimson', 'Willy', '2017-11-13', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Ekins', 'Sheffield', '2017-12-05', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Grebbin', 'Pablo', '2021-04-21', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Kummerlowe', 'Alon', '2020-11-28', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Pescott', 'Elnore', '2016-02-20', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Cathersides', 'Rivkah', '2019-03-08', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Cardenas', 'Marijn', '2018-04-04', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Doubrava', 'Ara', '2018-10-12', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Greenacre', 'Eamon', '2019-10-25', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Berling', 'Jackie', '2021-07-15', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Dummer', 'Rhiamon', '2020-03-06', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Fort', 'Davina', '2017-09-01', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Raiston', 'Willi', '2020-02-06', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Rake', 'Saw', '2020-04-01', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Greenrod', 'Efrem', '2016-07-28', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Scallon', 'Caterina', '2016-04-24', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Szapiro', 'Halette', '2020-09-10', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Moors', 'Liana', '2022-05-21', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Morphet', 'Alix', '2019-01-14', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Tremoulet', 'Hedvige', '2016-08-14', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Halton', 'Gamaliel', '2016-06-10', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Keeton', 'Cindee', '2016-06-27', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Fronzek', 'Crysta', '2021-04-08', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Pigne', 'Nickey', '2022-02-06', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Haw', 'Anabella', '2021-06-08', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Manie', 'Leann', '2021-09-21', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Chippendale', 'Mart', '2022-06-08', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Connal', 'Kasper', '2022-05-07', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Gibke', 'Yolanda', '2021-09-12', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Dadson', 'Sheryl', '2019-12-02', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Warlow', 'Gina', '2020-12-12', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Rubinovitch', 'Josefa', '2021-10-15', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Prinne', 'Valle', '2017-11-04', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Grealey', 'Hilton', '2018-06-17', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Itzkovich', 'Ber', '2020-09-13', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Kidds', 'Rikki', '2019-05-18', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Figgen', 'Lavina', '2020-08-24', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('MacLaig', 'Jelene', '2020-09-16', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Austwick', 'Lucine', '2019-01-11', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Ziemecki', 'Essie', '2019-12-05', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Caney', 'Edward', '2019-06-11', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Rowsell', 'Blair', '2017-02-03', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Stuckford', 'Kat', '2019-08-05', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Inker', 'Harrietta', '2019-12-18', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Westpfel', 'Joli', '2020-10-01', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Igo', 'Skye', '2021-06-02', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Gross', 'Cherrita', '2022-06-11', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Novotna', 'Allissa', '2021-01-02', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Goodfield', 'Roth', '2018-05-28', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Whaley', 'Ibrahim', '2019-11-16', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('MacMearty', 'Pat', '2016-07-17', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Croston', 'Anna-maria', '2017-08-09', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Lamberts', 'Zsazsa', '2016-08-12', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Tilmouth', 'Dudley', '2022-08-30', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Truder', 'Fonz', '2017-07-18', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('MacDermot', 'Devlin', '2019-02-11', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Boothman', 'Arleta', '2021-02-04', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Lister', 'Shell', '2021-07-09', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Rocks', 'Leah', '2019-10-10', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Bromige', 'Wallis', '2016-02-22', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Hansel', 'Noble', '2020-09-21', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Fairest', 'Pippo', '2021-05-26', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Uppett', 'Maxy', '2020-09-11', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Hallex', 'Jyoti', '2021-11-17', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Syers', 'Gretel', '2018-12-08', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Elflain', 'Alyssa', '2020-11-14', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Spandley', 'Cheslie', '2019-06-23', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Alcide', 'Tori', '2018-01-15', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Steddall', 'Kimball', '2021-07-19', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Fee', 'Gregg', '2020-09-07', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Druitt', 'Shanta', '2022-02-09', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Barendtsen', 'Steffane', '2018-04-11', true);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Belden', 'Romona', '2016-05-10', false);
insert into Student (lastname, firstname, birthdate, wantsnewsletter) values ('Treherne', 'Gabriela', '2021-01-20', true);