/* INSERT IN TO COURSE */
insert into Course (title) values ('Brown and yellow marshbird');
insert into Course (title) values ('Striped hyena');
insert into Course (title) values ('Armadillo, giant');
insert into Course (title) values ('Snake, eastern indigo');
insert into Course (title) values ('Ring-tailed possum');
insert into Course (title) values ('Heron, gray');
insert into Course (title) values ('Galah');
insert into Course (title) values ('Steller sea lion');
insert into Course (title) values ('Common wombat');
insert into Course (title) values ('Gull, dusky');
insert into Course (title) values ('Lesser flamingo');
insert into Course (title) values ('Crane, sarus');
insert into Course (title) values ('Asian false vampire bat');
insert into Course (title) values ('Yellow-crowned night heron');
insert into Course (title) values ('Eastern indigo snake');
insert into Course (title) values ('Lizard, blue-tongued');
insert into Course (title) values ('Common zebra');
insert into Course (title) values ('Australian magpie');
insert into Course (title) values ('Paradoxure');
insert into Course (title) values ('Cape white-eye');
insert into Course (title) values ('Southern right whale');
insert into Course (title) values ('Wallaby, tammar');
insert into Course (title) values ('Dove, mourning collared');
insert into Course (title) values ('Kangaroo, black-faced');
insert into Course (title) values ('Oriental white-backed vulture');
insert into Course (title) values ('Spotted wood sandpiper');
insert into Course (title) values ('Sea birds (unidentified)');
insert into Course (title) values ('African elephant');
insert into Course (title) values ('Owl, great horned');
insert into Course (title) values ('Cat, civet');
insert into Course (title) values ('Fringe-eared oryx');
insert into Course (title) values ('Kingfisher, malachite');
insert into Course (title) values ('White-throated monitor');
insert into Course (title) values ('Red-cheeked cordon bleu');
insert into Course (title) values ('Rose-ringed parakeet');
insert into Course (title) values ('Snake (unidentified)');
insert into Course (title) values ('Pacific gull');
insert into Course (title) values ('Dromedary camel');
insert into Course (title) values ('Whale, long-finned pilot');
insert into Course (title) values ('Alpaca');
insert into Course (title) values ('Otter, canadian river');
insert into Course (title) values ('Gaur');
insert into Course (title) values ('Dove, emerald-spotted wood');
insert into Course (title) values ('Gecko, ring-tailed');
insert into Course (title) values ('Lesser mouse lemur');
insert into Course (title) values ('Heron, black-crowned night');
insert into Course (title) values ('Wallaby, dama');
insert into Course (title) values ('Spoonbill, european');
insert into Course (title) values ('Otter, canadian river');
insert into Course (title) values ('Chestnut weaver');
insert into Course (title) values ('Godwit, hudsonian');
insert into Course (title) values ('Hare, arctic');
insert into Course (title) values ('Lion, steller sea');
insert into Course (title) values ('Tailless tenrec');
insert into Course (title) values ('Blue crane');
insert into Course (title) values ('Civet, small-toothed palm');
insert into Course (title) values ('Heron, gray');
insert into Course (title) values ('Waxbill, blue');
insert into Course (title) values ('Green heron');
insert into Course (title) values ('White-browed sparrow weaver');
insert into Course (title) values ('Deer, swamp');
insert into Course (title) values ('Common long-nosed armadillo');
insert into Course (title) values ('Mexican boa');
insert into Course (title) values ('Admiral, indian red');
insert into Course (title) values ('Red-necked wallaby');
insert into Course (title) values ('Armadillo, common long-nosed');
insert into Course (title) values ('Long-billed corella');
insert into Course (title) values ('Crake, african black');
insert into Course (title) values ('Canada goose');
insert into Course (title) values ('Great egret');
insert into Course (title) values ('Sun gazer');
insert into Course (title) values ('Waved albatross');
insert into Course (title) values ('White-winged dove');
insert into Course (title) values ('Galapagos penguin');
insert into Course (title) values ('Urial');
insert into Course (title) values ('Seal, common');
insert into Course (title) values ('Eleven-banded armadillo (unidentified)');
insert into Course (title) values ('African ground squirrel (unidentified)');
insert into Course (title) values ('Black and white colobus');
insert into Course (title) values ('Galapagos hawk');
insert into Course (title) values ('African jacana');
insert into Course (title) values ('Goose, knob-nosed');
insert into Course (title) values ('Wallaby, agile');
insert into Course (title) values ('Goose, andean');
insert into Course (title) values ('Wallaby, euro');
insert into Course (title) values ('Bat, madagascar fruit');
insert into Course (title) values ('Bleeding heart monkey');
insert into Course (title) values ('Ass, asiatic wild');
insert into Course (title) values ('Brown hyena');
insert into Course (title) values ('Long-necked turtle');
insert into Course (title) values ('Australian pelican');
insert into Course (title) values ('Snake-necked turtle');
insert into Course (title) values ('Seal, northern elephant');
insert into Course (title) values ('Dragon, asian water');
insert into Course (title) values ('Roller, lilac-breasted');
insert into Course (title) values ('Long-crested hawk eagle');
insert into Course (title) values ('Fox, grey');
insert into Course (title) values ('Phascogale, brush-tailed');
insert into Course (title) values ('Grey heron');
insert into Course (title) values ('Skink, african');
/* INSERT IN TO COURSEMATERIAL */
insert into CourseMaterial (course_id, url) values (1, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (2, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (3, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (4, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (5, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (6, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (7, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (8, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (9, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (10, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (11, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (12, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (13, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (14, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (15, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (16, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (17, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (18, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (19, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (20, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (21, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (22, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (23, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (24, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (25, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (26, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (27, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (28, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (29, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (30, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (31, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (32, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (33, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (34, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (35, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (36, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (37, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (38, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (39, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (40, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (41, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (42, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (43, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (44, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (45, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (46, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (47, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (48, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (49, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (50, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (51, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (52, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (53, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (54, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (55, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (56, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (57, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (58, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (59, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (60, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (61, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (62, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (63, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (64, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (65, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (66, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (67, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (68, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (69, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (70, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (71, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (72, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (73, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (74, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (75, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (76, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (77, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (78, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (79, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (80, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (81, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (82, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (83, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (84, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (85, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (86, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (87, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (88, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (89, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (90, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (91, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (92, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (93, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (94, 'http://dummyimage.com/100x100.png/dddddd/000000');
insert into CourseMaterial (course_id, url) values (95, 'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
insert into CourseMaterial (course_id, url) values (96, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (97, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (98, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into CourseMaterial (course_id, url) values (99, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into CourseMaterial (course_id, url) values (100, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
/* INSERT IN TO STUDENT */
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Arrow', 'Michele', '2018-01-04', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Gillinghams', 'Afton', '2016-04-07', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Lowry', 'Bert', '2016-03-20', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Stace', 'Sayer', '2017-06-08', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Russam', 'Hamlen', '2021-12-05', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Brosenius', 'Hakim', '2018-06-02', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Spuner', 'Ailsun', '2020-07-05', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('McCleod', 'Bartholomeo', '2021-10-16', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Streeten', 'Gayler', '2016-03-12', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('De Ruggiero', 'Bil', '2019-03-28', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Pinkstone', 'Batsheva', '2020-01-11', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Amdohr', 'Sherlocke', '2019-04-14', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Hearon', 'Adelbert', '2018-05-10', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Julyan', 'Heidie', '2020-07-26', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Aronow', 'Kirbie', '2017-06-30', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Lickorish', 'Guthry', '2018-02-08', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Palmer', 'Tait', '2021-02-25', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Dalgardno', 'Rita', '2020-10-22', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Fruen', 'Jeralee', '2022-08-16', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Pritchard', 'Marve', '2021-01-09', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Pine', 'Lani', '2020-09-10', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Basnett', 'Edithe', '2019-02-18', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Lackinton', 'Gris', '2019-02-16', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Sarfat', 'Eleonore', '2019-12-07', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('McGiffie', 'Ceil', '2020-10-06', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Sauter', 'Dev', '2018-12-20', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Duffrie', 'Carmine', '2020-02-02', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Pester', 'Haven', '2017-07-04', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Guilder', 'Forrester', '2022-10-12', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Molyneux', 'Evered', '2021-05-13', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Wrack', 'Bradley', '2020-04-04', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Birdsey', 'Nadya', '2017-02-18', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Lanegran', 'Domingo', '2018-12-21', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Grimsey', 'Conny', '2016-09-21', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Jarret', 'Anabal', '2017-05-11', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Confait', 'Vick', '2018-08-16', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Connue', 'Loni', '2017-09-16', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Bowling', 'Darrelle', '2019-11-26', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Ullock', 'Archy', '2016-10-13', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Eady', 'Heather', '2018-12-24', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Vasilkov', 'Kippy', '2020-12-12', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Pottiphar', 'Tallie', '2019-02-05', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Radborne', 'Tracy', '2019-06-03', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Alywen', 'Lindsay', '2019-03-25', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Westcott', 'Rochelle', '2019-10-02', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Hotson', 'Dav', '2020-03-29', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Anfosso', 'Randie', '2021-05-09', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Kingcote', 'Joceline', '2019-07-04', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Denes', 'Neysa', '2018-10-26', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Lightman', 'Ricky', '2018-11-09', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Khristoforov', 'Onfre', '2018-01-09', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('O''Currane', 'Levey', '2022-02-05', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Purveys', 'Sal', '2018-11-14', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Hellmore', 'Laina', '2021-10-19', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Mulqueen', 'Kerry', '2018-04-12', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Cheetam', 'Waverley', '2019-08-10', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('McPhelim', 'Romain', '2019-02-04', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Tethacot', 'Barnett', '2018-03-31', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Corden', 'Yank', '2017-05-21', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Lorking', 'Maiga', '2018-09-29', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Alpine', 'Mia', '2016-10-12', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('McDuffy', 'Godfry', '2019-11-12', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Sire', 'Giana', '2020-09-07', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Tour', 'Angelica', '2018-05-17', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Jouhan', 'Arabelle', '2019-02-15', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Morehall', 'Jeni', '2019-07-29', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('McKniely', 'Alisander', '2020-05-21', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Gulberg', 'Renelle', '2018-08-09', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Sitlinton', 'Lorri', '2016-07-08', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Rhyme', 'Chiarra', '2022-03-31', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Timny', 'Rochell', '2022-03-13', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Gowdie', 'Guss', '2022-06-12', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Pirot', 'Everett', '2022-04-24', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('McVeigh', 'Norby', '2016-01-27', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('O''Cullen', 'Randene', '2020-05-08', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Adrianello', 'Waylen', '2018-05-17', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Beldum', 'Deirdre', '2018-02-08', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Ledingham', 'Lotty', '2018-11-22', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Stutter', 'Jeanine', '2022-09-13', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Durn', 'Pattin', '2017-06-19', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Malamore', 'Marty', '2019-02-20', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Lodden', 'Averyl', '2016-04-30', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Manley', 'Pepi', '2020-01-07', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Cristoforo', 'Donn', '2020-01-22', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Canadine', 'Constantina', '2021-01-14', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Pateman', 'Shaine', '2018-10-21', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Brundale', 'Aaren', '2019-03-19', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Brozsset', 'Sherwynd', '2020-02-07', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('McHenry', 'Pamelina', '2020-11-10', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Schuler', 'Mufi', '2019-03-21', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Tranfield', 'Opaline', '2022-02-05', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Macias', 'Jacklin', '2020-01-01', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Bales', 'Elaine', '2020-02-19', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Langstone', 'Cornelius', '2022-04-22', false);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Palatini', 'Neysa', '2020-09-01', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Pauly', 'Gibby', '2020-03-20', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Bambridge', 'Lindsay', '2018-04-16', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Walenta', 'Olag', '2021-08-27', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Dawidman', 'Nicolis', '2016-04-17', true);
insert into Student (LastName, FirstName, birthdate, wantsNewsletter) values ('Yorath', 'Vivi', '2019-04-04', false);