insert into Course (id, title) values (1, 'Great horned owl');
insert into Course (id, title) values (2, 'White-winged dove');
insert into Course (id, title) values (3, 'Darker, african');
insert into Course (id, title) values (4, 'Musk ox');
insert into Course (id, title) values (5, 'Red-billed buffalo weaver');
insert into Course (id, title) values (6, 'Fox, grey');
insert into Course (id, title) values (7, 'Ox, musk');
insert into Course (id, title) values (8, 'Kafue flats lechwe');
insert into Course (id, title) values (9, 'Porcupine, tree');
insert into Course (id, title) values (10, 'Catfish, blue');
insert into Course (id, title) values (11, 'Badger, european');
insert into Course (id, title) values (12, 'Spotted wood sandpiper');
insert into Course (id, title) values (13, 'Cuis');
insert into Course (id, title) values (14, 'Indian giant squirrel');
insert into Course (id, title) values (15, 'Brindled gnu');
insert into Course (id, title) values (16, 'Starling, superb');
insert into Course (id, title) values (17, 'Roadrunner, greater');
insert into Course (id, title) values (18, 'Blue racer');
insert into Course (id, title) values (19, 'Emerald-spotted wood dove');
insert into Course (id, title) values (20, 'Vulture, griffon');
insert into Course (id, title) values (21, 'Hare, arctic');
insert into Course (id, title) values (22, 'Asian false vampire bat');
insert into Course (id, title) values (23, 'Coke''s hartebeest');
insert into Course (id, title) values (24, 'Tenrec, tailless');
insert into Course (id, title) values (25, 'Owl, white-browed');
insert into Course (id, title) values (26, 'Bettong, brush-tailed');
insert into Course (id, title) values (27, 'Beaver, north american');
insert into Course (id, title) values (28, 'Boa, cook''s tree');
insert into Course (id, title) values (29, 'Woolly-necked stork');
insert into Course (id, title) values (30, 'Frilled lizard');
insert into Course (id, title) values (31, 'Grant''s gazelle');
insert into Course (id, title) values (32, 'Penguin, magellanic');
insert into Course (id, title) values (33, 'Racer, american');
insert into Course (id, title) values (34, 'Little brown bat');
insert into Course (id, title) values (35, 'Indian jackal');
insert into Course (id, title) values (36, 'Finch, common melba');
insert into Course (id, title) values (37, 'Antelope, four-horned');
insert into Course (id, title) values (38, 'Golden jackal');
insert into Course (id, title) values (39, 'Yellow baboon');
insert into Course (id, title) values (40, 'Snowy egret');
insert into Course (id, title) values (41, 'Hawk, galapagos');
insert into Course (id, title) values (42, 'Slender loris');
insert into Course (id, title) values (43, 'Mongoose, yellow');
insert into Course (id, title) values (44, 'Bee-eater, carmine');
insert into Course (id, title) values (45, 'Barasingha deer');
insert into Course (id, title) values (46, 'Eagle, crowned');
insert into Course (id, title) values (47, 'Bleu, blue-breasted cordon');
insert into Course (id, title) values (48, 'Pelican, great white');
insert into Course (id, title) values (49, 'Stilt, black-winged');
insert into Course (id, title) values (50, 'Deer, savannah');
insert into Course (id, title) values (51, 'Glider, feathertail');
insert into Course (id, title) values (52, 'Pocket gopher (unidentified)');
insert into Course (id, title) values (53, 'Marmot, yellow-bellied');
insert into Course (id, title) values (54, 'Openbill stork');
insert into Course (id, title) values (55, 'Falcon, peregrine');
insert into Course (id, title) values (56, 'Otter, giant');
insert into Course (id, title) values (57, 'Nile crocodile');
insert into Course (id, title) values (58, 'Black-winged stilt');
insert into Course (id, title) values (59, 'Greater adjutant stork');
insert into Course (id, title) values (60, 'Capuchin, brown');
insert into Course (id, title) values (61, 'Sea birds (unidentified)');
insert into Course (id, title) values (62, 'Mongoose, eastern dwarf');
insert into Course (id, title) values (63, 'Skunk, striped');
insert into Course (id, title) values (64, 'White-rumped vulture');
insert into Course (id, title) values (65, 'Parrot, hawk-headed');
insert into Course (id, title) values (66, 'Buffalo, african');
insert into Course (id, title) values (67, 'Kangaroo, western grey');
insert into Course (id, title) values (68, 'Drongo, fork-tailed');
insert into Course (id, title) values (69, 'Albatross, waved');
insert into Course (id, title) values (70, 'Turaco, violet-crested');
insert into Course (id, title) values (71, 'Sheep, red');
insert into Course (id, title) values (72, 'Red-knobbed coot');
insert into Course (id, title) values (73, 'Black spider monkey');
insert into Course (id, title) values (74, 'Squirrel, thirteen-lined');
insert into Course (id, title) values (75, 'Black-backed jackal');
insert into Course (id, title) values (76, 'Little grebe');
insert into Course (id, title) values (77, 'Wattled crane');
insert into Course (id, title) values (78, 'Crane, sandhill');
insert into Course (id, title) values (79, 'African jacana');
insert into Course (id, title) values (80, 'Rattlesnake, dusky');
insert into Course (id, title) values (81, 'American badger');
insert into Course (id, title) values (82, 'Siskin, yellow-rumped');
insert into Course (id, title) values (83, 'American woodcock');
insert into Course (id, title) values (84, 'American black bear');
insert into Course (id, title) values (85, 'Phalarope, grey');
insert into Course (id, title) values (86, 'Cat, ringtail');
insert into Course (id, title) values (87, 'Raccoon, crab-eating');
insert into Course (id, title) values (88, 'Rock dove');
insert into Course (id, title) values (89, 'Fox, arctic');
insert into Course (id, title) values (90, 'Moccasin, water');
insert into Course (id, title) values (91, 'Reedbuck, bohor');
insert into Course (id, title) values (92, 'Elk, Wapiti');
insert into Course (id, title) values (93, 'Sally lightfoot crab');
insert into Course (id, title) values (94, 'Paca');
insert into Course (id, title) values (95, 'Blue-tongued lizard');
insert into Course (id, title) values (96, 'Langur, hanuman');
insert into Course (id, title) values (97, 'Eurasian hoopoe');
insert into Course (id, title) values (98, 'Stork, european');
insert into Course (id, title) values (99, 'Caracara, yellow-headed');
insert into Course (id, title) values (100, 'Heron, little');